SELECT
  1 + 2 * 3,
  (4 / 2) - 1,
  CASE WHEN a = 1 THEN 'one' WHEN a = 2 THEN 'two' ELSE 'other' END,
  CASE a WHEN 1 THEN 'one' ELSE 'other' END,
  a IS NULL,
  b IS NOT NULL,
  c IN (1, 2, 3),
  d NOT IN (4, 5),
  e BETWEEN 1 AND 10,
  f NOT BETWEEN 20 AND 30,
  g LIKE '%test%',
  h NOT LIKE 'a_b',
  EXISTS (SELECT 1 FROM t2 WHERE t2.id = t1.id),
  NOT EXISTS (SELECT * FROM t3),
  COUNT(*),
  SUM(DISTINCT val),
  MAX(val),
  MIN(val),
  AVG(val),
  GROUP_CONCAT(name ORDER BY id SEPARATOR ', '),
  EXTRACT(YEAR FROM date_col),
  CAST(val AS SIGNED),
  CONVERT(val, CHAR),
  POSITION('a' IN 'abc'),
  TRIM(BOTH ' ' FROM str),
  SUBSTRING(str FROM 2 FOR 3)
FROM t1;
